# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build and Deploy
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js with the latest version
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Ensures the latest stable version of Node.js 20.x
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build
        run: npm run build
        env:
          BASE_PATH: "/hunterwoodall-portfolio"

      # Upload build artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ".output/public" # Update this path if your build output differs

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .output/public
          branch: gh-pages
